### ISSUE TITLE
how in VS code

### ISSUE THREAD

**Issue by IshaanDixit07** [DmitrijVC/ultrasc-py#1]

**Comment by IshaanDixit07** [comment]
@DmitrijVC =========

**Comment by FssAy** [comment]
This version is [outdated](https://github.com/DmitrijVC/ultrasc-py#outdated). If you are using virtual environment, it's pretty much the same as for PyCharm, but if you are using global Python interpreter just type `pip install git+https://github.com/DmitrijVC/ultrasc-py.git#egg=ultrasc`

**Comment by IshaanDixit07** [comment]
Ok
